# Generated by Django 3.2 on 2021-04-20 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('User_Role', models.CharField(db_column='User_Role', max_length=10, null=True)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, db_column='created_on', null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, db_column='updated_on', null=True)),
            ],
        ),
    ]
