# Generated by Django 3.2 on 2021-04-20 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Map_Role_User',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.role')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
