# Generated by Django 3.2 on 2021-04-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_map_role_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='map_role_user',
            name='CreatedOn',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='map_role_user',
            name='UpdatedOn',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
