# Generated by Django 3.2 on 2021-04-20 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0003_auto_20210420_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('isPermanent', models.BooleanField(default=False, null=True)),
                ('locality', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('pincode', models.IntegerField(max_length=6)),
                ('phone', models.IntegerField(max_length=10)),
                ('Alt_Phone', models.IntegerField(max_length=10)),
                ('landmark', models.CharField(max_length=255)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
