# Generated by Django 3.2 on 2021-04-20 12:13

from django.db import migrations
import phone_field.models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31),
        ),
    ]
