# Generated by Django 3.2 on 2021-04-20 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App', '0005_alter_address_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(max_length=10),
        ),
        migrations.CreateModel(
            name='Social',
            fields=[
                ('Id', models.AutoField(primary_key=True, serialize=False)),
                ('Facebook', models.CharField(max_length=2048)),
                ('Twitter', models.CharField(max_length=2048)),
                ('instagram', models.CharField(max_length=2048)),
                ('whatsapp', models.CharField(max_length=2048)),
                ('CreatedOn', models.DateTimeField(auto_now_add=True, null=True)),
                ('UpdatedOn', models.DateTimeField(auto_now=True, null=True)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
