# Generated by Django 3.2 on 2021-04-21 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_auto_20210420_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Alt_Phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='phone',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='address',
            name='pincode',
            field=models.IntegerField(),
        ),
    ]
