# Generated by Django 3.1.8 on 2021-04-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_auto_20210421_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='Alt_Phone',
            field=models.IntegerField(blank=True),
        ),
    ]
