# Generated by Django 3.2 on 2021-04-20 05:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyKey',
            field=models.CharField(db_column='company_key', db_index=True, default='b9b69c8339', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserKey',
            field=models.CharField(db_column='user_key', db_index=True, default='c8523c04d7', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='UserKey'),
        ),
    ]
