# Generated by Django 3.2 on 2021-04-20 05:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlus', '0002_auto_20210420_1102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='CompanyKey',
            field=models.CharField(db_column='company_key', db_index=True, default='bbf73d9868', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserKey',
            field=models.CharField(db_column='user_key', db_index=True, default='7174a2f5c0', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='UserKey'),
        ),
    ]
