# Generated by Django 3.1.8 on 2021-04-23 06:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userPlus', '0012_auto_20210421_1828'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='Company',
        ),
        migrations.AlterField(
            model_name='company',
            name='CompanyKey',
            field=models.CharField(db_column='company_key', db_index=True, default='525d81c096', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='UserKey',
            field=models.CharField(db_column='user_key', db_index=True, default='63e60d4e8e', editable=False, max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9a-zA-Z]*$', 'Only alphanumeric characters are allowed.')], verbose_name='UserKey'),
        ),
    ]
